In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [4]:
# 对于单个张量，我们可以直接调⽤load和save函数分别读写它们
x = torch.arange(4)
torch.save(x, 'data/x-file')

In [5]:
x2 = torch.load("data/x-file")
x, x2

(tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]))

In [8]:
# 存储张量列表
y = torch.zeros(4)
torch.save([x, y], 'data/x-files')
x2, y2 = torch.load('data/x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [9]:
# 存储张量字典
mydict = {'x': x, 'y': y}
torch.save(mydict, 'data/mydict')
mydict2 = torch.load('data/mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [10]:
# 保存模型
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [11]:
# 将模型的参数存储在⼀个叫做“mlp.params”的⽂件中
torch.save(net.state_dict(), 'data/mlp.params')

In [13]:
# 加载模型
clone=MLP()
clone.load_state_dict(torch.load("data/mlp.params"))
Y==clone(X)

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])