In [1]:
import torch
from torch import nn

In [2]:
import torch
from torch import nn
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
net(X)

tensor([[-0.0618],
        [-0.1947]], grad_fn=<AddmmBackward0>)

In [4]:
# 参数访问
print(net)
# 可以发现0和2是全连接层，可以访问其w和b
print(net[0].state_dict())
print(net[2].state_dict())

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)
OrderedDict([('weight', tensor([[-0.3097, -0.1792,  0.1525, -0.2298],
        [ 0.4597, -0.1911,  0.4723,  0.1521],
        [-0.4802,  0.1474, -0.0386,  0.2222],
        [ 0.0101, -0.3311, -0.2875, -0.0062],
        [ 0.0580,  0.1718,  0.2807, -0.3547],
        [-0.0087, -0.1747,  0.4310,  0.2876],
        [-0.3737,  0.0846,  0.4955,  0.3069],
        [-0.3015,  0.3796,  0.2246, -0.4177]])), ('bias', tensor([-0.4689,  0.2814, -0.2959,  0.3440,  0.1201, -0.0706,  0.2030,  0.1164]))])
OrderedDict([('weight', tensor([[ 0.3482, -0.1273, -0.2183,  0.1126,  0.1316, -0.1739, -0.2847,  0.2712]])), ('bias', tensor([0.0639]))])


In [6]:
# 获取参数数值，参数是复合的对象，包含值、梯度和额外信息
# 获取b
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)
#获取w
print(type(net[2].weight))
print(net[2].weight)
print(net[2].weight.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([0.0639], requires_grad=True)
tensor([0.0639])
<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([[ 0.3482, -0.1273, -0.2183,  0.1126,  0.1316, -0.1739, -0.2847,  0.2712]],
       requires_grad=True)
tensor([[ 0.3482, -0.1273, -0.2183,  0.1126,  0.1316, -0.1739, -0.2847,  0.2712]])


In [7]:
# 访问所有参数
print(*[(name, param.shape) for name, param in net[0].named_parameters()])
print(*[(name, param.shape) for name, param in net.named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


In [8]:
net.state_dict()['2.bias'].data

tensor([0.0639])