In [4]:
"""
张量与Numpy的ndarray类似。但深度学习框架⼜⽐Numpy的ndarray多⼀些重要功能：
⾸先，GPU很好地⽀持加速计算，⽽NumPy仅⽀持CPU计算；
其次，张量类⽀持⾃动微分。这些功能使得张量类更适合深度学习
"""
import torch

In [5]:
# 类似numpy的array
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
# 类似numpy.arrange
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# 指定数据类型
torch.arange(12, dtype=torch.float32)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [8]:
# 张量的维度
x.shape

torch.Size([12])

In [9]:
# 获取shape在第0维的数值
print(x.shape[0])
print(x.size(0))

12
12


In [10]:
# 维度转换
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
# 如果变化成二维矩阵时，只需要指定一个维度，另外一个维度会被自动计算
# x.reshape(3,4)等价于x.reshape(-1,4)或x.reshape(3,-1)
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
# 零矩阵
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
# 单位矩阵
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
#标准正态分布矩阵
torch.randn(3, 4)

tensor([[ 0.7682,  0.0734,  0.3239, -1.3015],
        [ 0.9683,  1.0871,  1.9214, -1.0443],
        [ 1.1669, -0.2660, -1.2642,  1.2277]])

In [40]:
# 默认 + - * / 或者**运算都是对应位置元素进行计算
# **运算符是求幂运算
# 数学函数也是单个元素计算
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y, x - y, x * y, x ** y, torch.exp(x))

tensor([ 3,  4,  6, 10]) tensor([-1,  0,  2,  6]) tensor([ 2,  4,  8, 16]) tensor([ 1,  4, 16, 64]) tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [51]:
# 点乘
x = torch.arange(1, 3)
y = torch.arange(3, 5)
print(torch.dot(x, y))  # 点乘
print(torch.sum(x * y))  # 等价于dot

tensor(11)
tensor(11)


In [57]:
# 矩阵相乘
x = torch.arange(1, 10).reshape(3,3)
print(x)
torch.mm(x,x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [18]:
"""
张量连结
dim=0按行连接
dim=1按列连接
"""
x = torch.ones((3, 3))
y = torch.zeros((3, 3))
torch.cat((x, y), dim=0)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch.cat((x, y), dim=1)

tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])

In [20]:
# 逻辑比较，是对应位置进行运算
x == y

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [48]:
x = torch.arange(1, 10).reshape(-1, 3)
print(x)
print(x.sum())  # sum等聚合函数不指定维度，对全部元素进行相加
print(x.sum(axis=0))  # 按行加
print(x.sum(axis=1))  # 按列加
print(x.sum(axis=0, keepdims=True))  # 保持维度
print(x.sum(axis=1, keepdims=True))  # 保持维度

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(45)
tensor([12, 15, 18])
tensor([ 6, 15, 24])
tensor([[12, 15, 18]])
tensor([[ 6],
        [15],
        [24]])
tensor([[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]])


In [49]:
# cumsum，增量和
print(x)
x.cumsum(axis=0)  # 1行和2行结果保存到2，2和3结果保存到3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


tensor([[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]])

In [63]:
# L2范数运算
# sum(sqrt(xi^2))
u = torch.tensor([3.0, 4.0])
print(torch.norm(u))
# L1范数
# sum(abs(xi))
print(torch.sum(torch.abs(u)))

tensor(5.)
tensor(7.)


In [22]:
"""
torch的广播和numpy一样
"""
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
"""
对于某个维度只有一维的张量和numpy一样会自动广播进行对齐后计算
"""
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [24]:
# 索引和切⽚
x = torch.randn((3, 4))
x

tensor([[ 1.1287,  0.3021, -0.6453,  0.6403],
        [-0.0911, -0.5203,  0.0556,  0.2882],
        [ 0.0153,  2.4225, -0.1487,  0.2871]])

In [25]:
# -1表示最后一个元素，对于高维数据来说，就是其最高维的最后一组元素
x[-1]

tensor([ 0.0153,  2.4225, -0.1487,  0.2871])

In [26]:
# 切片是左闭右开
x[0:2]

tensor([[ 1.1287,  0.3021, -0.6453,  0.6403],
        [-0.0911, -0.5203,  0.0556,  0.2882]])

In [27]:
# 内存节约
"""
下面说明了x+x的计算结果，生成了新的内存空间
这可能是不可取的，原因有两个：
1. ⾸先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在⼀秒内多次
更新所有参数。通常情况下，我们希望原地执⾏这些更新；
2. 如果我们不原地更新，其他引⽤仍然会指向旧的内存位置，这样我们的某些代码可能会⽆意中引⽤旧
的参数
"""
before = id(x)
x = x + x
id(x) == before

False

In [28]:
"""
使用[:]操作进行原地更新
"""
before = id(x)
x[:] = x + x
id(x) == before

True

In [35]:
"""
复制
"""
x = torch.arange(20, dtype=torch.float32).reshape(5, 4)
y = x
z = x.clone()
x[0] = -1
print(x, y, z, sep="\n----------------\n")

tensor([[-1., -1., -1., -1.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
----------------
tensor([[-1., -1., -1., -1.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
----------------
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [41]:
# 转换为numpy对象
type(x), type(x.numpy())

(torch.Tensor, numpy.ndarray)

In [36]:
"""
转换为python的基本数据，item()只能对单个tensor元素使用
"""
x[0, 0].item(), type(x[0, 0].item())

(-1.0, float)